version: '3.8'

services:
  crewai-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./static/uploads:/app/static/uploads
      - ./app_logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - CHROMA_DB_PATH=/app/chroma_db
      - UPLOAD_DIR=/app/static/uploads
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          memory: 1G

  ollama:  #Explicit Ollama service
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  #Persist downloaded models
    restart: unless-stopped

volumes:  #Named volumes
  ollama_data: